# Sleep Logs Analysis

# Intro

This article intends to provide complete analysis of given sleep logs. The purposes of the analysis are: 

- Ensure the quality of sleep at the present time;
- Define main external and internal factors influence the quality of sleep and well being;
- Develop a plan to improve, maintain, and enhance quality of sleep.

So the information presented here will be more focused on the analysis data itself than its preparing and formatting techniques. But it will have well documented source code and brief explanations in the article itself.

# Data and Methodology

Future methods of processing the data depends on given sources. There will be presented data from two distinct tables of different formats: **markdown** - `.md`, and **comma-separated values (CSV)** - `.txt` or `.csv`. The data of these sources must follow common table structure for future processing and interpreting. That's why these files will undergo several stages of the preparatory process, **scv-source** table's format chosen as more preferable due it's data precision:

1. Fetching **markdown** table by title (source code `md_extract`):
   This is performed in `md_extract.py` by using such packages as [Markdown](https://pypi.org/project/Markdown/) and [Beautiful Soup](https://pypi.org/project/beautifulsoup4/);
4. Renaming columns of the **md-source** table to match the names of the **csv-source** table;
5. Adding new and removing unnecessry columns to the **md-source** for compatibility with **csv-source**;
6. Changing `Duration` column to timestamp to make it easier to operate with;
7. Generate dates for rows, **md-source** has data aranged sequentially in ascending date order.
   The earliest day of the **csv_source** used for generation;
8. Formatting **Sleep Time** and **Wake Time** of the both tables.
9. Finally, concatination of two tables to get data in a single-form table.

## Brief explanation of Summary analysis

TODO

## Brief explanation of Plots Analysis

TODO

In [1]:
import tables_prep as tp

tp.table.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 2025-11-04 to 2025-10-26
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sleep Time  20 non-null     object
 1   Wake Time   20 non-null     object
 2   Duration    20 non-null     object
 3   Notes       9 non-null      object
dtypes: object(4)
memory usage: 800.0+ bytes

In [2]:
tp.table.head()

,Sleep Time,Wake Time,Duration,Notes
Date,,,,
2025-11-04,10:04 PM,06:00 AM,7h 56m,Bad sleep. Woke up at about 1:00am and went to...
2025-11-03,09:56 PM,06:00 AM,8h 4m,"Good sleep. Fell asleep quickly, woke up easil..."
2025-11-02,10:07 PM,06:57 AM,8h 50m,Slept well. Woke up at night twice without the...
2025-11-01,09:58 PM,06:00 AM,8h 2m,Feel good. Didn' see or forgot a dream. Hard t...
2025-10-31,10:06 PM,06:00 AM,7h 54m,Was hard to wake up. Vivid dreams. I felt a sl...

In [3]:
tp.table.tail()

           Sleep Time Wake Time Duration Notes
Date
2025-10-22   11:47 PM   7:00 AM   7h 13m   NaN
2025-10-23   10:53 PM   6:00 AM   7h 07m   NaN
2025-10-24   10:05 PM   7:06 AM   9h 01m   NaN
2025-10-25   10:09 PM   6:00 AM   7h 50m   NaN
2025-10-26    9:58 PM   6:00 AM   8h 02m   NaN

# References

- [Markdown Official Website](https://daringfireball.net/projects/markdown/)
- [Beautiful Soup Official Website](https://www.crummy.com/software/BeautifulSoup/)
- [Markdown in PyPI](https://pypi.org/project/Markdown/)
- [Beautiful Soup in PyPI](https://pypi.org/project/beautifulsoup4/)